/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a one-time code to a phone number */
        post: operations["startOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a one-time code for a session */
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a Google ID token for a session */
        post: operations["googleSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account with email and password */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in as the seeded demo player (mock API only) */
        post: operations["demoSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in player's profile */
        get: operations["getMyProfile"];
        /** Create or update the profile (onboarding) */
        put: operations["saveMyProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/handle-available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is this handle free? */
        get: operations["checkHandle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the avatar URL
         * @description The mock accepts a data URL. The backend should issue a presigned upload
         *     (`POST /me/avatar/upload-url`) and accept the resulting object URL here.
         */
        put: operations["updateMyAvatar"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Games the player hosts or has joined */
        get: operations["listMyGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/stat-approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stat lines awaiting this player's review */
        get: operations["listMyStatApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Supported sports, with their result and stat schemas
         * @description Adding a sport is a backend row, not a frontend deploy. Stat entry renders from this.
         */
        get: operations["listSports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player directory */
        get: operations["listPlayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{handleOrId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A player by handle or id */
        get: operations["getPlayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{handleOrId}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A player's match history
         * @description Derived from approved results, never stored on the profile.
         */
        get: operations["listPlayerMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public games
         * @description Private games are never listed; they are reachable by link only.
         */
        get: operations["listGames"];
        put?: never;
        /** Host a game */
        post: operations["createGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A game by id or slug */
        get: operations["getGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a game (host only) */
        patch: operations["updateGame"];
        trace?: never;
    };
    "/games/{gameId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a game (host only) */
        post: operations["cancelGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a game completed (host only) */
        post: operations["completeGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everyone on this game, including requests and the waitlist */
        get: operations["listParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join, request to join, or take a waitlist place
         * @description Idempotent. The resulting status depends on the game: `confirmed` when it is open with
         *     room, `requested` when the host approves joins, `waitlisted` when it is full.
         */
        post: operations["joinGame"];
        /** Leave a game */
        delete: operations["leaveGame"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/participants/{playerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a player (host only) */
        delete: operations["removeParticipant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/participants/{playerId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Approve or decline a join request (host only) */
        put: operations["decideParticipant"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who has paid and who owes
         * @description PlayChale records payment; it does not move money in this version.
         */
        get: operations["listGamePayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/payments/{playerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Record a payment state
         * @description A player may mark their own line as paid (`marked_paid`). Only the host may
         *     `confirm` or `waive`.
         */
        put: operations["updatePayment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result, player stat lines and MVP votes */
        get: operations["getGameResults"];
        /**
         * Submit or replace the result (host only)
         * @description Replacing a result bumps `version` and invalidates approvals recorded against the old one.
         */
        put: operations["submitGameResult"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/player-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Submit per-player stat lines (host only)
         * @description The host's own line is auto-approved; every other line awaits that player's review.
         */
        put: operations["submitPlayerStats"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/player-stats/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Approve or reject your own stat line
         * @description A line counts toward career stats only when it is approved AND the game result is
         *     approved AND the line was approved against the current result version.
         */
        put: operations["reviewMyStats"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/mvp-vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cast or change your MVP vote (participants only) */
        put: operations["voteMvp"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @example GAME_FULL */
                code: string;
                /** @description Human-readable and safe to show to users */
                message: string;
                /** @description Which input was rejected, for form errors */
                field?: string;
            };
        };
        Page: {
            items: unknown[];
            /** @description Opaque keyset cursor; null on the last page. */
            nextCursor: string | null;
        };
        Money: {
            /** @description 2500 = GHS 25.00; 0 means free */
            amountMinor: number;
            /** @example GHS */
            currency: string;
        };
        AuthUser: {
            id: string;
            /** Format: email */
            email?: string | null;
            /** @description E.164 */
            phone?: string | null;
        };
        Session: {
            user: components["schemas"]["AuthUser"] | null;
            /** @description The account's player profile, if onboarding is complete. Distinct from the account id. */
            playerId: string | null;
            hasProfile: boolean;
        };
        Credentials: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        Sport: {
            /** @example football */
            code: string;
            /** @example Football */
            name: string;
            isTeamSport: boolean;
            defaultCapacity: number;
            /** @description Share of stat lines that must be approved before a result counts. */
            approvalThreshold: number;
            resultFields: components["schemas"]["StatField"][];
            statFields: components["schemas"]["StatField"][];
        };
        StatField: {
            /** @example goals */
            key: string;
            /** @example Goals */
            label: string;
            /** @enum {string} */
            type: "number" | "boolean";
        };
        PlayerSummary: {
            id: string;
            /** @description Without the @; the profile lives at /@{handle} */
            handle: string;
            name: string;
            avatarUrl: string;
        };
        Player: components["schemas"]["PlayerSummary"] & {
            bio?: string;
            /** @description Sport code */
            mainSport: string;
            sports?: string[];
            skillLevel?: components["schemas"]["SkillLevel"];
            locationText?: string;
            city?: string;
            /** @description Self-rated playing style. Never mixed with verified stats. */
            attributes: {
                pace?: number;
                shooting?: number;
                passing?: number;
                dribbling?: number;
                defending?: number;
                physical?: number;
            };
            /** @description Derived from approved results only. Empty until a result is approved. */
            careerStats: components["schemas"]["CareerStats"][];
            /** Format: date-time */
            createdAt?: string;
        };
        CareerStats: {
            sport: string;
            gamesPlayed: number;
            wins: number;
            losses: number;
            draws: number;
            mvps: number;
            noShows: number;
            /** @description Sport-specific totals keyed by Sport.statFields[].key, e.g. { goals: 42 } */
            counters: {
                [key: string]: number;
            };
            /** Format: date-time */
            lastGameAt?: string | null;
        };
        ProfileInput: {
            name: string;
            /** @description Generated from the name when omitted */
            handle?: string;
            /** @description Sport codes */
            sports: string[];
            bio?: string;
            skillLevel?: components["schemas"]["SkillLevel"];
            locationText?: string;
            city?: string;
            attributes?: {
                [key: string]: number;
            };
        };
        /** @enum {string} */
        SkillLevel: "Beginner" | "Intermediate" | "Competitive" | "All Levels";
        /** @enum {string} */
        ParticipantStatus: "requested" | "waitlisted" | "confirmed" | "declined" | "cancelled" | "removed";
        Participant: {
            player: components["schemas"]["PlayerSummary"];
            status: components["schemas"]["ParticipantStatus"];
            /** @enum {string} */
            role: "host" | "player";
            /** @description Waitlist position, 1-based */
            position?: number | null;
            /** @enum {string|null} */
            attendance?: "present" | "no_show" | null;
            /** Format: date-time */
            joinedAt?: string;
        };
        Game: {
            id: string;
            slug: string;
            title: string;
            /** @description Sport code */
            sport: string;
            /** @enum {string} */
            status: "scheduled" | "cancelled" | "completed";
            /** @enum {string} */
            visibility: "public" | "private";
            /**
             * Format: date-time
             * @description The instant the game starts
             */
            startsAt: string;
            /**
             * @description IANA zone the host chose
             * @example Africa/Accra
             */
            timezone: string;
            durationMinutes?: number;
            locationText: string;
            /** @description Set once venues exist; null today */
            venueId?: string | null;
            lat?: number | null;
            lng?: number | null;
            fee: components["schemas"]["Money"];
            /** @enum {string} */
            paymentMethod?: "none" | "momo_manual";
            /** @description Host's mobile-money number, shown to participants */
            paymentHandle?: string | null;
            capacity: number;
            confirmedCount: number;
            /** @enum {string} */
            joinPolicy: "open" | "approval";
            skillLevel: components["schemas"]["SkillLevel"];
            imageUrl: string;
            host: components["schemas"]["PlayerSummary"];
            /** @description Present on a single game, omitted in lists */
            participants?: components["schemas"]["Participant"][];
            /** @description A few confirmed players, so list cards can show an avatar stack without fetching every roster. Never the full roster — use `participants` for that. */
            participantPreview?: components["schemas"]["PlayerSummary"][];
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            cancelledAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
            viewer?: components["schemas"]["GameViewer"];
        };
        /** @description State specific to the requester, kept out of the shared shape. */
        GameViewer: {
            participation?: {
                status: components["schemas"]["ParticipantStatus"];
                /** @enum {string} */
                role: "host" | "player";
                position?: number | null;
            } | null;
            canManage: boolean;
            payment?: components["schemas"]["PaymentLine"] | null;
        };
        GameInput: {
            title: string;
            sport: string;
            /** Format: date-time */
            startsAt: string;
            /** @default Africa/Accra */
            timezone: string;
            /** @default 90 */
            durationMinutes: number;
            locationText: string;
            capacity: number;
            fee?: components["schemas"]["Money"];
            paymentHandle?: string;
            /**
             * @default open
             * @enum {string}
             */
            joinPolicy: "open" | "approval";
            skillLevel?: components["schemas"]["SkillLevel"];
            /**
             * @default public
             * @enum {string}
             */
            visibility: "public" | "private";
            imageUrl?: string;
        };
        /** @description Every field optional; only what is sent changes. */
        GameUpdate: {
            title?: string;
            /** Format: date-time */
            startsAt?: string;
            durationMinutes?: number;
            locationText?: string;
            capacity?: number;
            fee?: components["schemas"]["Money"];
            paymentHandle?: string;
            /** @enum {string} */
            joinPolicy?: "open" | "approval";
            skillLevel?: components["schemas"]["SkillLevel"];
            /** @enum {string} */
            visibility?: "public" | "private";
            imageUrl?: string;
        };
        PaymentLine: {
            gameId: string;
            playerId: string;
            player?: components["schemas"]["PlayerSummary"];
            amount: components["schemas"]["Money"];
            /** @enum {string} */
            status: "owed" | "marked_paid" | "confirmed" | "waived";
            /** @enum {string} */
            method?: "cash" | "momo_manual";
            /** Format: date-time */
            markedPaidAt?: string | null;
            /** Format: date-time */
            confirmedAt?: string | null;
            note?: string | null;
        };
        GameResult: {
            gameId: string;
            enteredBy: string;
            /** @description Keyed by Sport.resultFields[].key, e.g. { teamAScore: 3 } */
            resultData: {
                [key: string]: number;
            };
            /** @enum {string} */
            status: "pending" | "approved" | "disputed";
            approvalThreshold: number;
            approvalsCount: number;
            rejectionsCount: number;
            /** @description Bumped on resubmission; approvals are recorded against a version */
            version: number;
            /** Format: date-time */
            approvedAt?: string | null;
        };
        ResultInput: {
            resultData: {
                [key: string]: number;
            };
        };
        PlayerGameStat: {
            gameId: string;
            playerId: string;
            player?: components["schemas"]["PlayerSummary"];
            sport: string;
            stats: {
                [key: string]: number | boolean;
            };
            showedUp: boolean;
            /** @enum {string|null} */
            outcome?: "win" | "loss" | "draw" | null;
            /** @enum {string} */
            approval: "pending" | "approved" | "rejected";
            /** Format: date-time */
            approvedAt?: string | null;
            resultVersion: number;
            note?: string | null;
        };
        PlayerStatInput: {
            playerId: string;
            stats: {
                [key: string]: number | boolean;
            };
            showedUp: boolean;
            /** @enum {string} */
            outcome?: "win" | "loss" | "draw";
        };
        MvpVote: {
            gameId: string;
            voterId: string;
            playerId: string;
        };
        GameResults: {
            result: components["schemas"]["GameResult"] | null;
            playerStats: components["schemas"]["PlayerGameStat"][];
            mvpVotes: components["schemas"]["MvpVote"][];
            mvp?: components["schemas"]["PlayerSummary"] | null;
        };
        StatApproval: components["schemas"]["PlayerGameStat"] & {
            game: components["schemas"]["GameSummary"] | null;
            result: components["schemas"]["GameResult"] | null;
        };
        GameSummary: {
            id: string;
            slug: string;
            title: string;
            sport: string;
            /** Format: date-time */
            startsAt: string;
            timezone?: string;
            locationText?: string;
            imageUrl: string;
        };
        MatchRecord: {
            game: components["schemas"]["GameSummary"];
            stats: {
                [key: string]: number | boolean;
            };
            /** @enum {string|null} */
            outcome?: "win" | "loss" | "draw" | null;
            /** @enum {string} */
            approval: "pending" | "approved" | "rejected";
            wasMvp?: boolean;
            result?: components["schemas"]["GameResult"] | null;
        };
    };
    responses: {
        /** @description Invalid input (`INVALID_*` codes) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `UNAUTHENTICATED`: no valid session */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `FORBIDDEN`: signed in, but not allowed */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `PROFILE_REQUIRED`: signed in but onboarding is unfinished */
        ProfileRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `NOT_HOST`: only the host can do this */
        NotHost: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `*_NOT_FOUND` */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `RATE_LIMITED` */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Opaque `nextCursor` from the previous page */
        Cursor: string;
        Limit: number;
        /** @description Handle (without @) or player id */
        HandleOrId: string;
        /** @description Game id or slug */
        GameId: string;
        PlayerId: string;
        /** @description Retried writes on a flaky connection must not double-apply. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description `pc_session=<token>; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000` (Secure in production) */
        SessionCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    startOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Local or E.164; the server normalises (0244… → +233244…)
                     * @example 0244123456
                     */
                    phone: string;
                };
            };
        };
        responses: {
            /** @description Code sent */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        challengeId: string;
                        /** Format: date-time */
                        expiresAt: string;
                        resendAfterSeconds: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    challengeId: string;
                    /** @example 123456 */
                    code: string;
                };
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description `OTP_INVALID` or `OTP_EXPIRED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    googleSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    idToken: string;
                };
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description `EMAIL_TAKEN` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    demoSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ProfileRequired"];
        };
    };
    saveMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            /** @description `HANDLE_TAKEN` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    checkHandle: {
        parameters: {
            query: {
                handle: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        handle: string;
                        available: boolean;
                        /** @description Why not, when unavailable: taken | reserved | invalid */
                        reason?: string;
                    };
                };
            };
        };
    };
    updateMyAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    avatarUrl: string;
                };
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            403: components["responses"]["ProfileRequired"];
        };
    };
    listMyGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hosted and joined games */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        hosted: components["schemas"]["Game"][];
                        joined: components["schemas"]["Game"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    listMyStatApprovals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending approvals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatApproval"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    listSports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"][];
                };
            };
        };
    };
    listPlayers: {
        parameters: {
            query?: {
                /** @description Opaque `nextCursor` from the previous page */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                /** @description Filter by sport code */
                sport?: string;
                /** @description Free-text name search */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of players */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["Player"][];
                    };
                };
            };
        };
    };
    getPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Handle (without @) or player id */
                handleOrId: components["parameters"]["HandleOrId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPlayerMatches: {
        parameters: {
            query?: {
                /** @description Opaque `nextCursor` from the previous page */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                /** @description Handle (without @) or player id */
                handleOrId: components["parameters"]["HandleOrId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of matches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["MatchRecord"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listGames: {
        parameters: {
            query?: {
                /** @description Opaque `nextCursor` from the previous page */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                /** @description Sport code; omit for all */
                sport?: string;
                /** @description Only games starting at or after this instant */
                from?: string;
                /** @description Only games starting before this instant */
                to?: string;
                /** @description 0 returns free games only */
                maxFeeMinor?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of games, soonest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["Game"][];
                    };
                };
            };
        };
    };
    createGame: {
        parameters: {
            query?: never;
            header?: {
                /** @description Retried writes on a flaky connection must not double-apply. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ProfileRequired"];
        };
    };
    getGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            403: components["responses"]["NotHost"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            403: components["responses"]["NotHost"];
        };
    };
    completeGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            403: components["responses"]["NotHost"];
        };
    };
    listParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    joinGame: {
        parameters: {
            query?: never;
            header?: {
                /** @description Retried writes on a flaky connection must not double-apply. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated game */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ProfileRequired"];
            404: components["responses"]["NotFound"];
            /** @description `GAME_FULL` when the game has no waitlist, or `GAME_CLOSED` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leaveGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated game */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    removeParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
                playerId: components["parameters"]["PlayerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated game */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            403: components["responses"]["NotHost"];
        };
    };
    decideParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
                playerId: components["parameters"]["PlayerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "approve" | "decline";
                };
            };
        };
        responses: {
            /** @description Updated game */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            403: components["responses"]["NotHost"];
            /** @description `GAME_FULL` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listGamePayments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment lines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentLine"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    updatePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
                playerId: components["parameters"]["PlayerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "owed" | "marked_paid" | "confirmed" | "waived";
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Updated line */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentLine"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getGameResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResults"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    submitGameResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultInput"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResult"];
                };
            };
            403: components["responses"]["NotHost"];
        };
    };
    submitPlayerStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerStatInput"][];
            };
        };
        responses: {
            /** @description Saved lines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerGameStat"][];
                };
            };
            403: components["responses"]["NotHost"];
        };
    };
    reviewMyStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "approve" | "reject";
                    /** @description What the player disputes */
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Updated line */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerGameStat"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    voteMvp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game id or slug */
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    playerId: string;
                };
            };
        };
        responses: {
            /** @description Vote */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MvpVote"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
}
